In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('regs.csv')

In [4]:
df.head(10)

Unnamed: 0 code_module code_presentation  id_student gender  \
0           0         AAA             2013J       11391      M   
1           1         AAA             2013J       28400      F   
2           2         AAA             2013J       30268      F   
3           3         AAA             2013J       31604      F   
4           4         AAA             2013J       32885      F   
5           5         AAA             2013J       38053      M   
6           6         AAA             2013J       45462      M   
7           7         AAA             2013J       45642      F   
8           8         AAA             2013J       52130      F   
9           9         AAA             2013J       57506      M   

                 region      highest_education imd_band age_band  \
0   East Anglian Region       HE Qualification  90-100%     55<=   
1              Scotland       HE Qualification   20-30%    35-55   
2  North Western Region  A Level or Equivalent   30-40%    35-55   
3     South East Region  A Level or Equivalent   50-60%    35-55   
4  West Midlands Region     Lower Than A Level   50-60%     0-35   
5                 Wales  A Level or Equivalent   80-90%    35-55   
6              Scotland       HE Qualification   30-40%     0-35   
7  North Western Region  A Level or Equivalent  90-100%     0-35   
8   East Anglian Region  A Level or Equivalent   70-80%     0-35   
9          South Region     Lower Than A Level   70-80%    35-55   

   num_of_prev_attempts  studied_credits disability final_result  \
0                     0              240          N         Pass   
1                     0               60          N         Pass   
2                     0               60          Y    Withdrawn   
3                     0               60          N         Pass   
4                     0               60          N         Pass   
5                     0               60          N         Pass   
6                     0               60          N         Pass   
7                     0              120          N         Pass   
8                     0               90          N         Pass   
9                     0               60          N         Pass   

   date_registration  date_unregistration  module_presentation_length  \
0             -159.0                268.0                         268   
1              -53.0                268.0                         268   
2              -92.0                 12.0                         268   
3              -52.0                268.0                         268   
4             -176.0                268.0                         268   
5             -110.0                268.0                         268   
6              -67.0                268.0                         268   
7              -29.0                268.0                         268   
8              -33.0                268.0                         268   
9             -103.0                268.0                         268   

   days_studied  activities_engaged  total_clicks  assessments_completed  \
0          40.0               196.0         934.0               0.833333   
1          80.0               430.0        1435.0               0.833333   
2          12.0                76.0         281.0               0.000000   
3         123.0               663.0        2158.0               0.833333   
4          70.0               352.0        1034.0               0.833333   
5         143.0               723.0        2445.0               0.833333   
6          90.0               355.0        1492.0               0.833333   
7         105.0               531.0        1428.0               0.833333   
8         122.0               593.0        1894.0               0.833333   
9          90.0               403.0        1319.0               0.833333   

   average_assessment_score  
0                      82.0  
1                      66.4  
2                       0.0  
3                

In [5]:
#Delete rows with result = Distinction
df1 = df.loc[df['final_result'] != "Distinction"]

In [6]:
df = df1
df.shape

(24102, 21)

In [7]:
# Transform the data
# Transform non-numerical into numerical col
from sklearn.preprocessing import LabelEncoder

for column in df.columns:
  if df[column].dtype == np.float64:
    continue
  df[column] = LabelEncoder().fit_transform(df[column])

In [8]:
df

Unnamed: 0  code_module  code_presentation  id_student  gender  region  \
0               0            0                  1           2       1       0   
1               1            0                  1          28       0       6   
2               2            0                  1          41       0       5   
3               3            0                  1          51       0       7   
4               4            0                  1          56       0      11   
...           ...          ...                ...         ...     ...     ...   
26259       24097            6                  3       21298       0       3   
26260       24098            6                  3       21305       1       1   
26262       24099            6                  3       21426       0      10   
26264       24100            6                  3       21457       0       8   
26265       24101            6                  3       21557       0       7   

       highest_education  imd_band  age_band  num_of_prev_attempts  \
0                      1         9         2                     0   
1                      1         2         1                     0   
2                      0         3         1                     0   
3                      0         5         1                     0   
4                      2         5         0                     0   
...                  ...       ...       ...                   ...   
26259                  2         8         0                     0   
26260                  1         6         1                     0   
26262                  2         1         0                     0   
26264                  0         2         0                     0   
26265                  2         9         1                     0   

       studied_credits  disability  final_result  date_registration  \
0                   37           0             1             -159.0   
1                    5           0             1              -53.0   
2                    5           1             2              -92.0   
3                    5           0             1              -52.0   
4                    5           0             1             -176.0   
...                ...         ...           ...                ...   
26259                0           0             1              -64.0   
26260                0           0             2              -45.0   
26262                0           0             0               -4.0   
26264                0           1             1             -129.0   
26265                0           0             2              -49.0   

       date_unregistration  module_presentation_length  days_studied  \
0                    268.0                           5          40.0   
1                    268.0                           5          80.0   
2                     12.0                           5          12.0   
3                    268.0                           5         123.0   
4                    268.0                           5          70.0   
...                    ...                         ...           ...   
26259                269.0                           6           9.0   
26260                 48.0                           6           4.0   
26262                269.0                           6           5.0   
26264                269.0                           6          24.0   
26265                101.0                           6          13.0   

       activities_engaged  total_clicks  assessments_completed  \
0                   196.0         934.0               0.833333   
1                   430.0        1435.0               0.833333   
2                    76.0         281.0               0.000000   
3                   663.0        2158.0               0.833333   
4                   352.0        1034.0               0.833333   
...                   ...           ...                    ...   
26259        

In [9]:
df['Result'] = df['final_result']

In [10]:
df = df.drop('final_result', axis = 1)

In [11]:
df

Unnamed: 0  code_module  code_presentation  id_student  gender  region  \
0               0            0                  1           2       1       0   
1               1            0                  1          28       0       6   
2               2            0                  1          41       0       5   
3               3            0                  1          51       0       7   
4               4            0                  1          56       0      11   
...           ...          ...                ...         ...     ...     ...   
26259       24097            6                  3       21298       0       3   
26260       24098            6                  3       21305       1       1   
26262       24099            6                  3       21426       0      10   
26264       24100            6                  3       21457       0       8   
26265       24101            6                  3       21557       0       7   

       highest_education  imd_band  age_band  num_of_prev_attempts  \
0                      1         9         2                     0   
1                      1         2         1                     0   
2                      0         3         1                     0   
3                      0         5         1                     0   
4                      2         5         0                     0   
...                  ...       ...       ...                   ...   
26259                  2         8         0                     0   
26260                  1         6         1                     0   
26262                  2         1         0                     0   
26264                  0         2         0                     0   
26265                  2         9         1                     0   

       studied_credits  disability  date_registration  date_unregistration  \
0                   37           0             -159.0                268.0   
1                    5           0              -53.0                268.0   
2                    5           1              -92.0                 12.0   
3                    5           0              -52.0                268.0   
4                    5           0             -176.0                268.0   
...                ...         ...                ...                  ...   
26259                0           0              -64.0                269.0   
26260                0           0              -45.0                 48.0   
26262                0           0               -4.0                269.0   
26264                0           1             -129.0                269.0   
26265                0           0              -49.0                101.0   

       module_presentation_length  days_studied  activities_engaged  \
0                               5          40.0               196.0   
1                               5          80.0               430.0   
2                               5          12.0                76.0   
3                               5         123.0               663.0   
4                               5          70.0               352.0   
...                           ...           ...                 ...   
26259                           6           9.0                80.0   
26260                           6           4.0                18.0   
26262                           6           5.0                19.0   
26264                           6          24.0               108.0   
26265                           6          13.0                61.0   

       total_clicks  assessments_completed  average_assessment_score  Result  
0             934.0               0.833333                 82.000000       1  
1            1435.0               0.833333                 66.400000       1  
2             281.0               0.000000                  0.000000       2  
3            2158.0               0.833333                 76.000000       1  
4       

In [12]:
df.shape[1]

21

In [13]:
#spit the dataset
x = df.iloc[:, 15:20].values
x.shape

(24102, 5)

In [14]:
y=df.iloc[:, 20].values

In [15]:
#Split the dataset into 75% training and 25% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [16]:
#Use the random forest classifier model
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 10 , criterion = 'entropy', random_state = 0)
forest.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [17]:
# Get the accuracy on the training dataset
forest.score(x_train, y_train)

0.9640960389466696

In [18]:
#Show the confusion matrix and accuracy score for the model on the test data
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, forest.predict(x_test))

TN = cm[0][0]
TP = cm[1][1]
FN = cm[1][0]
FP = cm[0][1]

print(cm)
a1_score = ((TP + TN) / (TP +TN +FN + FP)  ) *100
print(a1_score)

[[ 748  310  639]
 [ 230 2358   24]
 [ 613   59 1045]]
85.18924849149752


In [27]:
#Performance prediction
categ = ['Student will fail', 'Student will pass', 'Student will withdraw']
custom_dt = [[12.0,61.0,284.0,0.330001,12.000000]]

In [28]:
print(categ[int(forest.predict(custom_dt))])

Student will withdraw
